# Site settings
title: NiMARE Sprint
email: alaird@fiu.edu
url: https://github.com/neurostuff/NiMARE
description: "Contribute to a new Python tool for neuroimaging meta-analysis"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

plugins:
  - jekyll-maps

# Footer settings
footer: NiMARE developers

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/phyzang
  - title: github
    url: https://github.com/neurostuff/NiMARE

# Build settings
markdown: kramdown
permalink: pretty
