# Site settings
title:  Coastal Coding for Reproducible Neuroimaging
email: alaird@fiu.edu
url: https://coastal-coding.github.io
description: "ReproNim+Nipype 2.0 / NiMARE @FIU in Miami"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: NiMARE developers

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/phyzang
  - title: github
    url: https://github.com/neurostuff/NiMARE

# Build settings
markdown: kramdown
permalink: pretty
